= Hyper Lang

Statycznie typowany język programowania transpilowany do JavaScript,
zaprojektowany z myślą o dużych projektach.

== Dlaczego

TypeScript rozwiązał typowanie JS, ale zostawił dwa uporczywe problemy:
fragmentację narzędziową (npm/yarn/pnpm, brak jednego standardu) i typowanie
bibliotek jako osobny wszechświat (`@types/*`, `DefinitelyTyped`, wrappery
pisane ręcznie). Hyper Lang celuje w oba naraz: jeden menedżer pakietów
(`vira`, inspirowany Cargo) i natywną obsługę bibliotek JS/TS bez wrapperów.

== Struktura repozytorium

[source]
----
src/            kompilator hyperc (Go) - lekser, parser, checker, codegen
vira/           menedżer pakietów vira, napisany w samym Hyper Lang
examples/       przykładowe programy .hyper
website/        wygenerowana strona projektu (patrz build.hyper)
build.hyper     generator website/index.html
build.rb        hook pre-buildowy pakietu (odpowiednik build.rs z Cargo)
vira.yml        manifest workspace'u (odpowiednik Cargo.toml)
----

== Szybki start

[source,bash]
----
cd src && go build -o ../bin/hyperc .
cd ..
./bin/hyperc run examples/hello.hyper
----

== Stan projektu (v0.1)

Zaimplementowane: lekser, parser, statyczny checker (typy prymitywne,
zgodność traitów, wyczerpujący `match`, arność wywołań, niemutowalność),
generator JS, CLI (`build`/`run`), obsługa błędów (`throw`/`try`/`catch`/
`finally`), aliasy w importach (`import { load as parseYaml } from "js-yaml"`).

`vira/` zawiera już działającą (nie tylko zaprojektowaną) menedżerkę
pakietów napisaną w samym Hyper Lang - parsuje `vira.yml`, rozwiązuje
zależności przez prawdziwe zapytania do rejestru npm, zapisuje `vira.lock`,
i potrafi wygenerować szkielet nowego projektu (`vira new <nazwa>`).

W budowie: pełna inferencja typów, generyki w codegenie, LSP, formatter,
rozwiązywanie importów pomiędzy plikami `.hyper` (dziś każdy plik kompiluje
się niezależnie), bootstrapping (hyperc napisany w samym Hyper Lang).

== Licencja

MIT - patrz link:LICENSE[]
