[app]
name       = "HackerAndroid"
version    = "0.1.0"
identifier = "pl.hackeros.android"
target     = "android"

[android]
min_sdk      = 24
target_sdk   = 34
compile_sdk  = 34
package      = "pl.hackeros.android"
