pub struct BuildIntegration {
    pub project_name: String,
    pub has_tauri: bool,
    pub has_gtk: bool,
    pub has_qt: bool,
}

impl BuildIntegration {
    pub fn new(project_name: impl Into<String>, has_tauri: bool, has_gtk: bool, has_qt: bool) -> Self {
        BuildIntegration {
            project_name: project_name.into(),
            has_tauri,
            has_gtk,
            has_qt,
        }
    }

    /// Generate a CMakeLists.txt that invokes cargo for the transpiled project.
    pub fn cmake(&self) -> String {
        let mut out = String::new();

        out.push_str("# Generated by Vira transpiler\n");
        out.push_str("# Integrates Rust/Cargo build into CMake\n\n");
        out.push_str("cmake_minimum_required(VERSION 3.20)\n");
        out.push_str(&format!("project({} LANGUAGES C CXX)\n\n", self.project_name));

        // Find cargo
        out.push_str("find_program(CARGO_BIN cargo REQUIRED)\n");
        out.push_str("find_program(VIRA_BIN vira)\n\n");

        // GTK integration
        if self.has_gtk {
            out.push_str("find_package(PkgConfig REQUIRED)\n");
            out.push_str("pkg_check_modules(GTK4 REQUIRED gtk4)\n\n");
        }

        // Qt integration
        if self.has_qt {
            out.push_str("find_package(Qt6 REQUIRED COMPONENTS Core Widgets Qml Quick)\n\n");
        }

        // Custom target: transpile Vira → Rust
        out.push_str("# Vira transpile step\n");
        out.push_str("add_custom_target(\n");
        out.push_str("    vira_transpile\n");
        out.push_str("    COMMAND ${VIRA_BIN} build ${CMAKE_SOURCE_DIR}\n");
        out.push_str("    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}\n");
        out.push_str("    COMMENT \"Transpiling Vira sources to Rust...\"\n");
        out.push_str("    VERBATIM\n");
        out.push_str(")\n\n");

        // Custom target: cargo build
        out.push_str("# Cargo build of transpiled Rust\n");
        out.push_str("add_custom_target(\n");
        out.push_str("    cargo_build ALL\n");
        out.push_str("    DEPENDS vira_transpile\n");
        out.push_str(&format!(
            "    COMMAND ${{CARGO_BIN}} build $<$<CONFIG:Release>:--release> \
             --manifest-path ${{CMAKE_SOURCE_DIR}}/.vira-out/Cargo.toml\n"
        ));
        out.push_str("    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/.vira-out\n");
        out.push_str("    COMMENT \"Building Rust output...\"\n");
        out.push_str("    VERBATIM\n");
        out.push_str(")\n\n");

        // Install
        out.push_str("install(\n");
        out.push_str(&format!(
            "    PROGRAMS ${{CMAKE_SOURCE_DIR}}/.vira-out/target/release/{}\n",
            self.project_name
        ));
        out.push_str("    DESTINATION bin\n");
        out.push_str(")\n");

        out
    }

    /// Generate a Makefile for direct use.
    pub fn makefile(&self) -> String {
        let name = &self.project_name;
        format!(
            r#"# Generated by Vira transpiler
# Makefile for {name}

VIRA    ?= vira
CARGO   ?= cargo
OUT_DIR := .vira-out

.PHONY: all build release clean run fmt check

all: build

## Transpile Vira → Rust, then build debug
build:
	$(VIRA) build .
	$(CARGO) build --manifest-path $(OUT_DIR)/Cargo.toml

## Transpile + cargo release build
release:
	$(VIRA) build --release .
	$(CARGO) build --release --manifest-path $(OUT_DIR)/Cargo.toml

## Run the project
run:
	$(VIRA) run .

## Format Vira sources
fmt:
	$(VIRA) fmt .

## Type-check without building
check:
	$(VIRA) check .

## Clean all build artifacts
clean:
	rm -rf $(OUT_DIR)

## Install to /usr/local/bin
install: release
	install -Dm755 $(OUT_DIR)/target/release/{name} /usr/local/bin/{name}
"#,
            name = name
        )
    }
}
