use crate::native_api::{NativeApi, NativeApiKind};

pub struct CargoGen {
    pub project_name: String,
    pub version: String,
    pub edition: String,
    pub native_apis: Vec<NativeApi>,
    pub extra_deps: Vec<(String, String)>,
    pub has_tauri: bool,
}

impl CargoGen {
    pub fn new(project_name: impl Into<String>, native_apis: Vec<NativeApi>) -> Self {
        let has_tauri = native_apis.iter().any(|a| a.kind == NativeApiKind::Tauri);
        CargoGen {
            project_name: project_name.into(),
            version: "0.1.0".to_owned(),
            edition: "2021".to_owned(),
            native_apis,
            extra_deps: Vec::new(),
            has_tauri,
        }
    }

    pub fn generate(&self) -> String {
        let mut out = String::new();

        out.push_str("# Generated by Vira transpiler\n");
        out.push_str("# DO NOT EDIT — regenerated on each vira build\n\n");

        out.push_str("[package]\n");
        out.push_str(&format!("name = \"{}\"\n", self.project_name));
        out.push_str(&format!("version = \"{}\"\n", self.version));
        out.push_str(&format!("edition = \"{}\"\n", self.edition));

        if self.has_tauri {
            out.push_str("build = \"build.rs\"\n");
        }

        out.push('\n');

        // Features
        if self.has_tauri {
            out.push_str("[features]\n");
            out.push_str("default = [\"tauri/devtools\"]\n\n");
        }

        out.push_str("[dependencies]\n");

        // Collect unique crate deps
        let mut seen = std::collections::HashSet::new();
        for api in &self.native_apis {
            for dep in &api.crates {
                if seen.insert(dep.name.clone()) {
                    out.push_str(&format!("{}\n", dep.to_toml_entry()));
                }
            }
        }

        // Common utility deps always included
        if !seen.contains("anyhow") {
            out.push_str("anyhow = \"1\"\n");
        }
        if !seen.contains("thiserror") {
            out.push_str("thiserror = \"1\"\n");
        }

        // scopeguard for `defer` keyword
        out.push_str("scopeguard = \"1\"\n");

        // tokio for async/spawn
        out.push_str("tokio = { version = \"1\", features = [\"full\"] }\n");

        // Extra user deps
        for (name, ver) in &self.extra_deps {
            if !seen.contains(name) {
                out.push_str(&format!("{name} = \"{ver}\"\n"));
            }
        }

        out.push('\n');

        // Build deps
        if self.has_tauri {
            out.push_str("[build-dependencies]\n");
            out.push_str("tauri-build = { version = \"2\", features = [] }\n\n");
        }

        // Profile optimization
        out.push_str("[profile.release]\n");
        out.push_str("opt-level = 3\n");
        out.push_str("lto = true\n");
        out.push_str("codegen-units = 1\n");
        out.push_str("strip = true\n\n");

        out.push_str("[profile.dev]\n");
        out.push_str("opt-level = 0\n");
        out.push_str("debug = true\n");

        out
    }

    /// Generate build.rs for Tauri projects
    pub fn generate_build_rs(&self) -> Option<String> {
        if !self.has_tauri {
            return None;
        }
        Some(
            "// Generated by Vira transpiler\nfn main() {\n    tauri_build::build()\n}\n"
                .to_owned(),
        )
    }
}
